# Generated by Django 4.0.5 on 2022-06-19 23:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, choices=[('f', 'Fruta'), ('l', 'Legume'), ('v', 'Verdura'), ('t', 'Ervas e temperos'), ('p', 'Produto lácteo (leite, queijo, etc.)'), ('o', 'Outros')], default='f', max_length=1)),
                ('cultura', models.CharField(blank=True, choices=[('t', 'Agricultura tradicional'), ('o', 'Agricultura orgânica')], default='t', help_text='Tipo de cultura do produto', max_length=1)),
                ('descricao', models.CharField(blank=True, help_text='Nome do alimento', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(help_text='Descrição resumida', max_length=500, null=True)),
                ('valor_estimado', models.CharField(blank=True, max_length=10, null=True)),
                ('disponibilidade', models.CharField(blank=True, choices=[('d', 'Disponível'), ('r', 'Reservada'), ('n', 'Não disponível')], default='d', max_length=1)),
                ('data_cadastro', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data_retirada', models.DateField(blank=True, null=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trocasolidaria.produtor')),
                ('produtos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trocasolidaria.alimento')),
            ],
        ),
    ]
