# Generated by Django 4.0.5 on 2022-06-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trocasolidaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cesta',
            name='valor_estimado',
            field=models.FloatField(),
        ),
    ]
