# Generated by Django 4.0.5 on 2022-06-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trocasolidaria', '0002_cesta_imagem_alter_cesta_valor_estimado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesta',
            name='imagem',
            field=models.ImageField(upload_to='uploads/imagens/'),
        ),
    ]
