# Generated by Django 4.0.5 on 2022-07-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trocasolidaria', '0003_alter_cesta_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesta',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='cesta',
            name='produtos',
        ),
        migrations.AddField(
            model_name='cesta',
            name='produtos',
            field=models.ManyToManyField(to='trocasolidaria.alimento'),
        ),
    ]
