# Generated by Django 4.0.5 on 2022-07-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trocasolidaria', '0004_remove_cesta_imagem_remove_cesta_produtos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cesta',
            name='produtos',
        ),
        migrations.AddField(
            model_name='cesta',
            name='alimento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome alimento 1: '),
        ),
        migrations.AddField(
            model_name='cesta',
            name='alimento_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome alimento 2: '),
        ),
        migrations.AddField(
            model_name='cesta',
            name='endereco',
            field=models.CharField(max_length=100, null=True, verbose_name='Endereço para retirada'),
        ),
        migrations.AddField(
            model_name='cesta',
            name='whatsapp',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
